# Generated by Django 4.0.3 on 2022-11-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prn', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer'), ('EE', 'Electrical'), ('CE', 'Civil'), ('ME', 'Mechanical'), ('IE', 'Instrumentation'), ('ENTC', 'Electronics and Tele.')], max_length=5)),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=3)),
            ],
        ),
    ]
