# Generated by Django 4.0.3 on 2022-11-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_issued', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='APP.student')),
            ],
        ),
    ]
