# Generated by Django 4.0.3 on 2022-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Instrumentation', 'Instrumentation'), ('Electronics and Tele.', 'Electronics and Tele.')], max_length=25),
        ),
    ]
